pokemons = [
    {
        "nombre": "Bulbasaur",
        "generacion": 1,
        "categoria": "Semilla",
        "tipos": ["Planta", "Veneno"],
        "peso_kg": 6.9,
        "altura_m": 0.7,
    },
    {
        "nombre": "Charizard",
        "generacion": 1,
        "categoria": "Llama",
        "tipos": ["Fuego", "Volador"],
        "peso_kg": 90.5,
        "altura_m": 1.7,
    },
    {
        "nombre": "Squirtle",
        "generacion": 1,
        "categoria": "Tortuguita",
        "tipos": ["Agua"],
        "peso_kg": 9.0,
        "altura_m": 0.5,
    },
    {
        "nombre": "Pikachu",
        "generacion": 1,
        "categoria": "Ratón",
        "tipos": ["Eléctrico"],
        "peso_kg": 6.0,
        "altura_m": 0.4,
    },
    {
        "nombre": "Jigglypuff",
        "generacion": 1,
        "categoria": "Globo",
        "tipos": ["Normal", "Hada"],
        "peso_kg": 5.5,
        "altura_m": 0.5,
    },
    {
        "nombre": "Eevee",
        "generacion": 1,
        "categoria": "Evolución",
        "tipos": ["Normal"],
        "peso_kg": 6.5,
        "altura_m": 0.3,
    },
    {
        "nombre": "Lucario",
        "generacion": 4,
        "categoria": "Aura",
        "tipos": ["Lucha", "Acero"],
        "peso_kg": 54.0,
        "altura_m": 1.2,
    },
    {
        "nombre": "Gardevoir",
        "generacion": 3,
        "categoria": "Envolvente",
        "tipos": ["Psíquico", "Hada"],
        "peso_kg": 48.4,
        "altura_m": 1.6,
    },
    {
        "nombre": "Greninja",
        "generacion": 6,
        "categoria": "Ninja",
        "tipos": ["Agua", "Siniestro"],
        "peso_kg": 40.0,
        "altura_m": 1.5,
    },
]
personajes_frieren = [
    {
        "nombre": "Frieren",
        "raza": "Elfo",
        "clase": "Mago",
        "edad": 1000,
        "afiliacion": ["Grupo de los Cuatro Héroes", "Grupo de Frieren"],
    },
    {
        "nombre": "Himmel",
        "raza": "Humano",
        "clase": "Héroe",
        "edad": 76,
        "afiliacion": ["Grupo de los Cuatro Héroes"],
    },
    {
        "nombre": "Fern",
        "raza": "Humano",
        "clase": "Mago",
        "edad": 19,
        "afiliacion": ["Grupo de Frieren", "Magos de Primera Clase"],
    },
    {
        "nombre": "Stark",
        "raza": "Humano",
        "clase": "Guerrero",
        "edad": 18,
        "afiliacion": ["Grupo de Frieren"],
    },
    {
        "nombre": "Heiter",
        "raza": "Humano",
        "clase": "Sacerdote",
        "edad": 100,
        "afiliacion": ["Grupo de los Cuatro Héroes"],
    },
    {
        "nombre": "Eisen",
        "raza": "Enano",
        "clase": "Guerrero",
        "edad": 120,
        "afiliacion": ["Grupo de los Cuatro Héroes"],
    },
    {
        "nombre": "Sein",
        "raza": "Humano",
        "clase": "Sacerdote",
        "edad": 28,
        "afiliacion": ["Grupo de Frieren"],
    },
    {
        "nombre": "Ubel",
        "raza": "Humano",
        "clase": "Mago",
        "edad": 19,
        "afiliacion": ["Magos de Primera Clase"],
    },
    {
        "nombre": "Aura la Guillotina",
        "raza": "Demonio",
        "clase": "Mago",
        "edad": 500,
        "afiliacion": ["Siete Sabios de la Destrucción"],
    },
    {
        "nombre": "Denken",
        "raza": "Humano",
        "clase": "Mago",
        "edad": 78,
        "afiliacion": ["Magos de Primera Clase", "Asociación Continental de Magia"],
    },
    {
        "nombre": "Serie",
        "raza": "Elfo",
        "clase": "Mago",
        "edad": 2000,
        "afiliacion": ["Asociación Continental de Magia"],
    },
    {
        "nombre": "Sense",
        "raza": "Humano",
        "clase": "Mago",
        "edad": 28,
        "afiliacion": ["Magos de Primera Clase", "Asociación Continental de Magia"],
    },
]
